apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: spoons
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: <base64 encoded>
  POSTGRES_PASSWORD: <base64 encoded>
---
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-secret
  namespace: spoons
  labels:
    app: postgres
type: Opaque
data:
  GOOGLE_CLIENT_ID: <base64 encoded>
  GOOGLE_CLIENT_SECRET: <base64 encoded>
---
apiVersion: v1
kind: Secret
metadata:
  name: nextauthjs-secret
  namespace: spoons
  labels:
    app: nextauthjs
type: Opaque
data:
  NEXTAUTH_SECRET: <base64 encoded>
  NEXTAUTH_URL: <base64 encoded>
