# Spoonmaster deployment - run that johnson
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoonmaster
  namespace: spoons
  labels:
    app: spoonmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spoonmaster
  template:
    metadata:
      labels:
        app: spoonmaster
    spec:
      imagePullSecrets:
        - name: spoonsregcred
      containers:
        - name: spoonmaster
          image: docker.prorickey.xyz/prorickey/spoonmaster:0.1.2
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: spoons
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: host
              containerPort: 7892
          volumeMounts:
            - mountPath: /var/spoonmaster/
              name: spoonmaster-data
      volumes:
        - name: spoonmaster-data
          persistentVolumeClaim:
            claimName: spoonmaster-pvc
---
# Spoonmaster service - strictly internal to the cluster
# and only allows the website to connect
apiVersion: v1
kind: Service
metadata:
  name: spoonmaster-service
  namespace: spoons
  labels:
    app: spoonmaster
spec:
  selector:
    app: spoonmaster
  ports:
    - protocol: TCP
      port: 7892
      targetPort: 7892
  type: ClusterIP
---
# Persistent Volume Claim for Spoonmaster static data
# Just allocates space on the disk outside the vm
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spoonmaster-pvc
  namespace: spoons
  labels:
    app: spoonmaster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---