# Spoons website deployment - three for no chance of
# downtime due to shenanigans
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoons-website
  namespace: spoons
  labels:
    app: spoons-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spoons-website
  template:
    metadata:
      labels:
        app: spoons-website
    spec:
      imagePullSecrets:
        - name: spoonsregcred
      containers:
        - name: spoons-website
          image: docker.prorickey.xyz/prorickey/spoons-website:0.1.0
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: spoons
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextauthjs-secret
                  key: NEXTAUTH_SECRET
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: nextauthjs-secret
                  key: NEXTAUTH_URL
          ports:
            - name: http
              containerPort: 3000
---
# Spoons website service - exposes a node port
# which is unaccessible to the world, which then
# is accessed through nginx for ssl
apiVersion: v1
kind: Service
metadata:
  name: spoons-service
  namespace: spoons
spec:
  selector:
    app: spoons-website
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer